# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVevkEsDt1wIJcI-QQ4939XJngrd3va4
"""

# IMAGE FEATURES: EfficientNet-B0
img_model = timm.create_model("efficientnet_b0", pretrained=True, num_classes=0, global_pool="avg").to(DEVICE)
img_model.eval()

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

def extract_features(img_link):
    """Extract EfficientNet embeddings for a given image."""
    try:
        if img_link.startswith("http"):
            response = requests.get(img_link, timeout=5)
            img = Image.open(BytesIO(response.content)).convert("RGB")
        else:
            img = Image.open(img_link).convert("RGB")

        img_tensor = transform(img).unsqueeze(0).to(DEVICE)
        with torch.no_grad():
            features = img_model(img_tensor).cpu().numpy().flatten()
        return features
    except:
        return np.zeros(img_model.num_features)

# Batch processing for efficiency
image_features = []
for i in tqdm(range(0, len(df), 200), desc="Extracting image batches"):
    batch_links = df["image_link"].iloc[i:i+200]
    batch_feats = [extract_features(link) for link in batch_links]
    image_features.append(np.vstack(batch_feats))

image_features = np.vstack(image_features)


# COMBINE TEXT + IMAGE FEATURES

X_text_all = np.hstack([X_brand_svd, X_text_svd, X_unit_svd, df[["value_scaled"]].values])
X_final = np.hstack([X_text_all, image_features])
y = df["price_scaled"].values

print(f" Final feature shape: {X_final.shape}")