# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVevkEsDt1wIJcI-QQ4939XJngrd3va4
"""

# NLP Pipeline
# Price prediction using text
df = pd.read_csv("train.csv", usecols=["catalog_content", "price", "image_link"])


def parse_catalog_content(text):

    text = str(text)
    extract = lambda p: re.search(p, text)

    item_name = extract(r"Item Name:\s*(.*?)\n")
    unit = extract(r"Unit:\s*(.*?)\n")
    value = extract(r"Value:\s*(.*?)\n")
    description = re.search(r"Product Description:\s*(.*)", text, flags=re.DOTALL)
    bullets = re.findall(r"Bullet Point \d+:\s*(.*)", text)

    value_num = 0.0
    if value:
        try:
            value_num = float(re.search(r"[\d\.]+", value.group(1)).group())
        except:
            pass

    return pd.Series([
        item_name.group(1).strip() if item_name else "",
        " ".join(bullets),
        description.group(1).strip() if description else "",
        unit.group(1).strip() if unit else "",
        value_num
    ])

df[["item_name", "bullet_points", "product_desc", "unit", "value"]] = df["catalog_content"].apply(parse_catalog_content)
df["price"] = df["price"].astype(float)


# TEXT CLEANING
def clean_text(text):

    text = re.sub(r"[^a-z0-9.,\-\(\)/ ]", "", str(text).lower()) "lower Casing"
    tokens = [w for w in text.split() if w not in stop_words]    "stopwords removal"
    return " ".join(tokens)

for col in ["item_name", "bullet_points", "product_desc", "unit"]:
    df[col] = df[col].fillna("").apply(clean_text)

# Remove units from item names
units = set(df["unit"].unique())
def remove_units(text):
    for u in units:
        if u and u in text:
            text = text.replace(u, "")
    return text.strip()
df["item_name"] = df["item_name"].apply(remove_units)

df["product_text"] = (df["bullet_points"] + " " + df["product_desc"]).str.strip().replace("", "missing info")
df.rename(columns={"item_name": "product_brand"}, inplace=True)


#  SCALE NUMERIC FEATURES

df["value"] = df["value"].fillna(0.0)
df["price"] = df["price"].fillna(df["price"].median())

df["value_log"] = np.log1p(df["value"])
df["price_log"] = np.log1p(df["price"])

scaler_value = StandardScaler()
scaler_price = StandardScaler()

df["value_scaled"] = scaler_value.fit_transform(df[["value_log"]])
df["price_scaled"] = scaler_price.fit_transform(df[["price_log"]])


# TEXT FEATURES: TF-IDF + SVD

tfidf_brand = TfidfVectorizer(max_features=15000, ngram_range=(1, 2))
tfidf_text = TfidfVectorizer(max_features=30000, ngram_range=(1, 2))
tfidf_unit = TfidfVectorizer(max_features=128)

X_brand = tfidf_brand.fit_transform(df["product_brand"])
X_text = tfidf_text.fit_transform(df["product_text"])
X_unit = tfidf_unit.fit_transform(df["unit"])

svd_brand = TruncatedSVD(n_components=3000, random_state=SEED)
svd_text = TruncatedSVD(n_components=5000, random_state=SEED)
svd_unit = TruncatedSVD(n_components=64, random_state=SEED)

X_brand_svd = svd_brand.fit_transform(X_brand)
X_text_svd = svd_text.fit_transform(X_text)
X_unit_svd = svd_unit.fit_transform(X_unit)